# Site settings
title: "My Testing Website"
description: "Welcome to my GitHub Pages site"
url: "https://wangc90.github.io"
baseurl: ""   # leave empty for user/organization pages

# Author info
author:
  name: "<Chao Wang>"
  email: "wangc90@uchicago.edu"

# Theme (choose a GitHub-supported theme)
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed  # optional RSS feed
  
<link rel="stylesheet" href="assets/css/style.css">
